### ISSUE TITLE
Feature request: filter conventional commit types

### ISSUE THREAD

**Issue by Uninen** [jaywcjlove/changelog-generator#113]
First, Thank You for this simple and easy to use tool! 🙏 

When using a changelog template you get something like this:

```
### Feature

- feat: my feature
```

when the conventional commit types are known, and when the template is used, it would be nice to be able to filter away the redundant types from the beginning of the commit message. Ie:

```
### Feature

- my feature

### Unkown

- notconventional: other commit
```

Latter is much more readable and human-friendly -- would be nice to be able to do this 👍

**Comment by jaywcjlove** [comment]
@Uninen Do you want to remove the `feat:` in the commit?

**Comment by Uninen** [comment]
Yes, for all the known conventional types.

**Comment by jaywcjlove** [comment]
@Uninen 

https://github.com/jaywcjlove/changelog-generator/blob/5257a7585a10f57c1cd284d471e9a4c6956ca73d/action.yml#L33-L36

**Comment by Uninen** [comment]
Don't understand the relevance of above. I've disabled the emojis already, but they don't affect the commit row text in any way (other than the emoji, that is)?

Again, here's the current output:

```
## Features:
- feat: add feature 1
- feat: add feature 2
```

Desired output:

```
## Features:
- add feature 1
- add feature 2
```

**Comment by jaywcjlove** [comment]
@Uninen 

https://github.com/jaywcjlove/changelog-generator/blob/f54db6b8770058dad806f8037c1c82ba416f4e7a/.github/workflows/changelog.yml#L72-L79

**Comment by Uninen** [comment]
Wow, brilliant. Thanks for adding this! 🙏
