### ISSUE TITLE
Log display template doesn't remove all unused headers

### ISSUE THREAD

**Issue by wjtje** [jaywcjlove/changelog-generator#114]
When using the following template with one commit `fix: some weird bug`

```md
## Bugs
{{fix}}
## Feature
{{feat}}
## Improve
{{refactor,perf,clean}}
## Misc 
{{chore,style,ci||🔶 Nothing change}}
## Unknown
{{__unknown__}}
```

The following changelog is generated:

```md
## Bugs
- fix: some weird bug 1234567 @username
## Improve
{{refactor,perf,clean}}
## Misc 
🔶 Nothing change
```

Instead of:

```md
## Bugs
- fix: some weird bug 1234567 @username
## Misc 
🔶 Nothing change
```

It seems like the RegEx on this [line](https://github.com/jaywcjlove/changelog-generator/blob/6de4323b033c680bc7584e5ee8da039d017d6322/src/utils.ts#L97C79-L97C79) is not correct.

**Comment by jaywcjlove** [comment]
@wjtje Upgrade `v1.9.4`

**Comment by wjtje** [comment]
The regex in the source code is now working, but I think that you forgot to compile it. Because the `dist/index.js` file still contains the old source code.

**Comment by jaywcjlove** [comment]
@wjtje has been recompiled. Upgrade `v1.9.5`
