### ISSUE TITLE
Any support for alternative repos?

### ISSUE THREAD

**Issue by Aetherinox** [jaywcjlove/changelog-generator#122]
Wrong title.

Is their possibly a way to support fetching info from another repo? Rather than the one the action is running on? I have a private repo which has the same content as the public one, and I'd like to be able to pull that data in the private repo. 

Didn't see any options for this.

**Comment by jaywcjlove** [comment]
@Aetherinox This requirement seems difficult. You can upload the `changelog` to 'released' in the private repository, and then download the `changelog` file from the public repository to read it.

**Comment by Aetherinox** [comment]
Appreciate the info. Yeah I'll probably end up having to do that.

I'm going to close the issue for now. Cleaning up my list. But thanks for the info.
