### ISSUE TITLE
Idea: revert commits list (newest to oldest)

### ISSUE THREAD

**Issue by RARgames** [jaywcjlove/changelog-generator#123]
Hey,
as usual, great project (works out of the box, not like the others I tried before recalling that I saw some cool actions in `react-md-editor`).

Here is 1 idea that I would find useful:
Revert commits list: Right now commits are sorted by date (oldest to newest), add input option to generate newest to oldest.

**Comment by jaywcjlove** [comment]
@RARgames Upgrade v2.1.0

https://github.com/jaywcjlove/changelog-generator/blob/fe7076a10af5c31498102de87446dd495b07d668/action.yml#L25-L28
